image: timescale/prometheus-postgresql-adapter
# number of connector pods to spawn
replicaCount: 1
# connection options to connect to a target db
## user used to connect to TimescaleDB
user: postgres
## the name of a Secret object containing the 
## password to connect to TimescaleDB indexed
## by the user name
passwordSecret: "some-secret-name"
host: 
  # For a hardcoded host name from another release set:
  #   nameTemplate: "{{ already-deployed-timescale.default.svc.cluster.local }}"
  # For a host name of a timescaledb instance
  # deployed in the same release (without a cluster override) set:
  #   nameTemplate: "{{ .Release.Name }}".default.svc.cluster.local
  nameTemplate: "{{ .Release.Name }}.default.svc.cluster.local"
port: 5432

# set your own limits
resources:
  requests:
    cpu: 1
    memory: 1Gi
  limits:
    cpu: 1
    memory: 1Gi
# https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
nodeSelector: {}