apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ template "connector.fullname" . }}
    chart: {{ template "connector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "connector.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "connector.fullname" . }}
    spec:
      containers:
        - image: {{ .Values.image }}
          imagePullPolicy: IfNotPresent
          name: {{ .Chart.Name }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests: 
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          ports:
            - containerPort: 9201
              name: connector-port
          env:
            - name: PGPORT
              value: {{ .Values.port | quote }}
            - name: PGUSER
              value: {{ .Values.user }}
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.password.secretName }}
                  key: {{ .Values.user }}
            - name: PGHOST
              value: {{ .Values.host }} 
          args:
            [
              -pg-ssl-mode=require,
              -pg-host=$(PGHOST),
              -pg-user=$(PGUSER),
              -pg-password=$(PGPASSWORD),
              -pg-port=$(PGPORT)
            ]
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{ toYaml . | indent 2 }}
      {{- end }}